### PR TITLE
Create factorial_iterative.rb

### PR DESCRIPTION
**Pull request by devtanumisra**

### CODE REVIEW

**Review by ShehrozIrfan — CHANGES_REQUESTED** [review]
Good work!
Just a minor update/change need to take input from user, something like asking the user:

"Please enter a number"

And once it gets the number and then it calculate the factorial and shows to user.

**Comment by devtanumisra** [comment]
> _ No description provided. _

Updated the change

**Review by ShehrozIrfan — APPROVED** [review]
LGTM

**Comment by ShehrozIrfan** [comment]
@devtanumisra 

Great 🚀

You can follow me and star this repo for further updates.
Have fun!

**Pull request merged**
