### PR TITLE
Largest Element in ARRAY

### PR DESCRIPTION
**Pull request by zilladeepak**
Code for finding Largest Element in ARRAY in ruby programming language

### CODE REVIEW

**Comment by zilladeepak** [comment]
Before I made a mistake due to some issues total files aren't added to staged files and I didn't observed it. Sorry for that. But now I recovered all the things and added them to staged files and added my file to it. Plzz Review it. Again sorry for the mistake before which was done.

**Comment by ShehrozIrfan** [comment]
Hey @zilladeepak !
No worries. You did the great job.
You can follow me and star this repository for further updates. 
Have fun  🙌🏼

**Comment by zilladeepak** [comment]
Will this still counts in hacktoberfest ? Because in the page it's shows that not accepted so it's not counted right?

**Comment by ShehrozIrfan** [comment]
Yes, if on the page it is written, not counted, then it won't be counted. Sadly!

**Pull request merged**
