### PR TITLE
Create file_create_edit_close.rb

### PR DESCRIPTION
**Pull request by p134c0d3**
- Created a Ruby program that creates a new .txt file, writes to it, and then closes the file
- File that is created is located in the directory that it is run in

### CODE REVIEW

**Comment by p134c0d3** [comment]
Ran program multiple times with no errors thrown. Let me know if any changes need to be made.

**Comment by p134c0d3** [comment]
Updated the file to allow for interactive prompts in the command line to show user input turned into the filename, and content of file created.

**Review by ShehrozIrfan — APPROVED** [review]
LGTM!

**Comment by ShehrozIrfan** [comment]
Hey @jpierce-coder 
Thank you for your contribution 🚀

**Comment by p134c0d3** [comment]
Of course, anytime. As I increase my skills in Ruby, I will be sure to add more. 🙂

**Pull request merged**
